language: java

branches:
  only:
    - master

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_OPTS="-Xmx4G"
    - MAVEN_OPTS="-Xmx4G"

before_script:
  - echo $JAVA_OPTS
  - echo $MAVEN_OPTS
  
script:
  - mvn -e -X test

after_success:
  - mvn coveralls:report -Ptravis