language: java

jdk:
  - oraclejdk8

before_script:
    - echo "MAVEN_OPTS='-Xmx1024m'" > ~/.mavenrc
    
script:
  - mvn cobertura:cobertura

after_success:
  - mvn coveralls:report -Ptravis
  - bash <(curl -s https://codecov.io/bash)
