language: java

jdk:
  - oraclejdk8

before_script:
  - echo "MAVEN_OPTS='-Xmx1024m'" > ~/.mavenrc
  - mvn cobertura:cobertura
  - mvn coveralls:report -Ptravis
  - bash <(curl -s https://codecov.io/bash)
